trigger:
  batch: true
  branches:
    include:
      - dev
      - master

pr:
  autoCancel: true
  branches:
    include:
      - '*'

pool: 'BuildVM'

jobs:
- job: 'MathCalAPP'
  steps:
    # Install .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetToolInstaller@1
      inputs:
        checkLatest: true
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: 'Source_code/MathOperationApp.sln'
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'build'
        projects: 'Source_code/MathOperationApp.sln'

