trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Az-Sc_devops'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      echo "=== Starting Azure VM Deployment==="

      RG_NAME="DevopsLearning-rg"
      LOCATION="francecentral"
      VM_NAME="slazbuildVM03"
      ADMIN_USER="azureuser"
      ADMIN_PASS="$VM_ADMIN_PASSWORD"

      VNET_NAME="TestVnet"
      SUBNET_NAME="TestSubnet"
      ADDRESS_SPACE="10.0.0.0/16"
      SUBNET_PREFIX="10.0.1.0/24"

      NSG_NAME="Devops_nsg"
      PUBLIC_IP_NAME="167.103.75.35"
      NIC_NAME="Learning_NIC"

      STORAGE_NAME="#V@r@n@si"  # unique storage name

      echo "=== Creating Resource Group ==="
      az group create --name $RG_NAME --location $LOCATION

      echo "=== Creating Storage Account ==="
      az storage account create \
        --name $STORAGE_NAME \
        --resource-group $RG_NAME \
        --location $LOCATION \
        --sku Standard_LRS

      echo "=== Creating Virtual Network ==="
      az network vnet create \
        --resource-group $RG_NAME \
        --name $VNET_NAME \
        --address-prefix $ADDRESS_SPACE \
        --subnet-name $SUBNET_NAME \
        --subnet-prefix $SUBNET_PREFIX

      echo "=== Creating NSG (NO Port Rules) ==="
      az network nsg create \
        --resource-group $RG_NAME \
        --name $NSG_NAME

      # NOTE: No SSH rule, NSG is empty

      echo "=== Creating Public IP ==="
      az network public-ip create \
        --resource-group $RG_NAME \
        --name $PUBLIC_IP_NAME \
        --sku Basic \
        --allocation-method Dynamic

      echo "=== Creating NIC ==="
      az network nic create \
        --resource-group $RG_NAME \
        --name $NIC_NAME \
        --vnet-name $VNET_NAME \
        --subnet $SUBNET_NAME \
        --network-security-group $NSG_NAME \
        --public-ip-address $PUBLIC_IP_NAME

      echo "=== Creating Linux VM ==="
      az vm create \
        --resource-group $RG_NAME \
        --name $VM_NAME \
        --nics $NIC_NAME \
        --image Ubuntu2204 \
        --admin-username $ADMIN_USER \
        --admin-password "$ADMIN_PASS" \
        --size Standard_B2s \
        --boot-diagnostics-storage $STORAGE_NAME \
        --location $LOCATION

      echo "=== VM Deployment Completed Successfully ==="